spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true
  datasource:
    driver-class-name: org.h2.Driver
  # secret properties
  profiles:
    include: secret