spring:
  datasource:
    driver-class-name: org.h2.Driver

  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  # secret properties
  profiles:
    include: secret

logging.level:
  org.hibernate.SQL: debug